// <auto-generated />
using System;
using Infraestructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(DevRiskContext))]
    partial class DevRiskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Domain.OperationCategory.Entity.OperationCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DaysAfterReferenceDate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DaysBeforeReferenceDate")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("EndValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InitialValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PriorityLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sector")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("OperationCategory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b617f8ac-689b-4e5c-8545-b6168510d1b5"),
                            DaysBeforeReferenceDate = 30,
                            Name = "EXPIRED",
                            PriorityLevel = 1,
                            Sector = 3
                        },
                        new
                        {
                            Id = new Guid("e01dd826-1f78-4ccf-802b-6606c5a37e3e"),
                            InitialValue = 1000000m,
                            Name = "HIGHRISK",
                            PriorityLevel = 2,
                            Sector = 2
                        },
                        new
                        {
                            Id = new Guid("3d05755d-2e9d-488a-b75b-220433912879"),
                            InitialValue = 1000000m,
                            Name = "MEDIUMRISK",
                            PriorityLevel = 3,
                            Sector = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
